# fly.toml app configuration file generated for little-violet-3254 on 2023-07-26T13:21:45-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "little-violet-3254"
primary_region = "mia"

[mounts]
  destination = "/pb/pb_data"
  source = "pb_data"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
